# Generated by Django 2.2 on 2019-04-22 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookTest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='book_id',
            new_name='book',
        ),
    ]
