# Generated by Django 2.2 on 2019-04-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookTest', '0002_auto_20190422_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pwd', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=20)),
            ],
        ),
    ]
