# Generated by Django 2.2 on 2019-04-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QC', '0002_account_application_host_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
