# Generated by Django 2.2 on 2019-04-19 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QC', '0003_auto_20190419_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='host_id',
            new_name='host',
        ),
        migrations.RenameField(
            model_name='phonenumber',
            old_name='account_id',
            new_name='account',
        ),
    ]
