# Generated by Django 2.2 on 2019-04-19 09:18

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('QC', '0004_auto_20190419_1613'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('manage', django.db.models.manager.Manager()),
            ],
        ),
    ]
